/* tslint:disable */
/* eslint-disable */
/**
 * assignment-template
 * This is a template repository for the first assignment in BVD 103 at McMaster Continuing Education.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response returned after a book is created or updated
 * @export
 * @interface BookResponse
 */
export interface BookResponse {
    /**
     * 
     * @type {string}
     * @memberof BookResponse
     */
    id: string;
}

/**
 * Check if a given object implements the BookResponse interface.
 */
export function instanceOfBookResponse(value: object): value is BookResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function BookResponseFromJSON(json: any): BookResponse {
    return BookResponseFromJSONTyped(json, false);
}

export function BookResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function BookResponseToJSON(json: any): BookResponse {
    return BookResponseToJSONTyped(json, false);
}

export function BookResponseToJSONTyped(value?: BookResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

