/* tslint:disable */
/* eslint-disable */
/**
 * assignment-template
 * This is a template repository for the first assignment in BVD 103 at McMaster Continuing Education.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request body for creating or updating a book
 * @export
 * @interface BookRequest
 */
export interface BookRequest {
    /**
     * 
     * @type {string}
     * @memberof BookRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof BookRequest
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof BookRequest
     */
    price: number;
    /**
     * 
     * @type {string}
     * @memberof BookRequest
     */
    author: string;
    /**
     * 
     * @type {string}
     * @memberof BookRequest
     */
    image: string;
}

/**
 * Check if a given object implements the BookRequest interface.
 */
export function instanceOfBookRequest(value: object): value is BookRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('author' in value) || value['author'] === undefined) return false;
    if (!('image' in value) || value['image'] === undefined) return false;
    return true;
}

export function BookRequestFromJSON(json: any): BookRequest {
    return BookRequestFromJSONTyped(json, false);
}

export function BookRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
        'price': json['price'],
        'author': json['author'],
        'image': json['image'],
    };
}

export function BookRequestToJSON(json: any): BookRequest {
    return BookRequestToJSONTyped(json, false);
}

export function BookRequestToJSONTyped(value?: BookRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'price': value['price'],
        'author': value['author'],
        'image': value['image'],
    };
}

