/* tslint:disable */
/* eslint-disable */
/**
 * assignment-template
 * This is a template repository for the first assignment in BVD 103 at McMaster Continuing Education.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SayHello200Response
 */
export interface SayHello200Response {
    /**
     * 
     * @type {string}
     * @memberof SayHello200Response
     */
    message: string;
}

/**
 * Check if a given object implements the SayHello200Response interface.
 */
export function instanceOfSayHello200Response(value: object): value is SayHello200Response {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function SayHello200ResponseFromJSON(json: any): SayHello200Response {
    return SayHello200ResponseFromJSONTyped(json, false);
}

export function SayHello200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SayHello200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function SayHello200ResponseToJSON(json: any): SayHello200Response {
    return SayHello200ResponseToJSONTyped(json, false);
}

export function SayHello200ResponseToJSONTyped(value?: SayHello200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

