/* tslint:disable */
/* eslint-disable */
/**
 * assignment-template
 * This is a template repository for the first assignment in BVD 103 at McMaster Continuing Education.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BookRequest,
  BookResponse,
} from '../models/index';
import {
    BookRequestFromJSON,
    BookRequestToJSON,
    BookResponseFromJSON,
    BookResponseToJSON,
} from '../models/index';

export interface CreateOrUpdateBookRequest {
    bookRequest: BookRequest;
}

/**
 * 
 */
export class BooksApi extends runtime.BaseAPI {

    /**
     */
    async createOrUpdateBookRaw(requestParameters: CreateOrUpdateBookRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BookResponse>> {
        if (requestParameters['bookRequest'] == null) {
            throw new runtime.RequiredError(
                'bookRequest',
                'Required parameter "bookRequest" was null or undefined when calling createOrUpdateBook().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/books`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BookRequestToJSON(requestParameters['bookRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BookResponseFromJSON(jsonValue));
    }

    /**
     */
    async createOrUpdateBook(requestParameters: CreateOrUpdateBookRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BookResponse> {
        const response = await this.createOrUpdateBookRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
